---
- name: Set name of iptables service ubuntu >= 16
  ansible.builtin.set_fact:
    iptables_service_name: netfilter-persistent
  when: ansible_distribution_version | int >= 16

- name: Check if ufw package is installed (on debian)
  ansible.builtin.shell: dpkg --get-selections ufw | grep install
  register: ufw_installed
  ignore_errors: true
  changed_when: false
  when:
    - firewall_disable_ufw

- name: Disable the ufw firewall (on debian, if configured)
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: false
  when:
    - not ansible_check_mode
    - firewall_disable_ufw
    - ufw_installed.rc == 0

- name: Update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ 3600 * 3 }}"
  check_mode: false

- name: Add persistance for iptables
  ansible.builtin.apt:
    name:
      - iptables
      - iptables-persistent
    force_apt_get: true

- name: Iptables templates
  ansible.builtin.template:
    src: "iptables.j2"
    dest: "/etc/iptables/{{ item }}"
    owner: root
    group: root
    mode: '0600'
    validate: bash -c 'cat %s | /sbin/iptables-restore --test'
  loop:
    - rules.v4
    - rules.v6
  register: iptables_templates

- name: Load new rules
  ansible.builtin.shell: "set -o pipefail && cat /etc/iptables/{{ item }} | iptables-restore --noflush"
  args:
    executable: bash
  loop:
    - rules.v4
    - rules.v6
  when:
    - iptables_templates is changed
    - not firewall_flush_on_change

- name: Restart iptables
  ansible.builtin.service:
    name: "{{ iptables_service_name }}"
    state: restarted
  when:
    - iptables_templates is changed
    - firewall_flush_on_change
